image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  stage: test
  services:
    - name: nativecode/test-radarr:latest
      alias: test-radarr
    - name: nativecode/test-sonarr:latest
      alias: test-sonarr
  script:
    - cat /etc/hosts
    - getent hosts $HOSTNAME | awk '{ print $1 }'
    - ./wait-for test-radarr 7878
    - ./wait-for test-sonarr 8989
    - ./test

publish:
  stage: publish
  script:
    - ./build
    - ./publish
