stages:
- test

image: node:latest

cache:
  paths:
  - node_modules

before_script:
- npm install

services:
- name: nativecode/test-radarr:latest
  alias: test-radarr
- name: nativecode/test-sonarr:latest
  alias: test-sonarr

test:
  stage: test
  script:
  - ./wait-for test-radarr 7878
  - ./wait-for test-sonarr 8989
  - ./test
