image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - ./wait-for ${HOSTNAME} 7878
    - ./wait-for ${HOSTNAME} 8989
    - ./test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - mkdir ~/.ssh -p
    - echo ${SSH_PUBLIC_KEY} > ~/.ssh/id_rsa.pub
    - echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa*
    - git checkout ${CI_COMMIT_REF_NAME}
    - ./publish

publish:
  stage: publish
  only:
    - tags
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - ./publish
