image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - echo RADARR_APIKEY
    - echo SONARR_APIKEY
    - ./wait-for ${HOSTNAME} 7878
    - ./wait-for ${HOSTNAME} 8989
    - ./test

publish:
  stage: publish
  script:
    - ./build
    - ./publish
