image: node:latest

stages:
- test
- publish

cache:
  paths:
  - node_modules

before_script:
- npm install

test:
  stage: test
  services:
  - nativecode/test-radarr:latest
  - nativecode/test-sonarr:latest
  script:
  - ./wait-for test-radarr 7878
  - ./wait-for test-sonarr 8989
  - ./test

publish:
  stage: publish
  script:
  - ./build
  - ./publish
