image: node:latest

stages:
  - test
  - prerelease
  - release

cache:
  paths:
    - node_modules

.testsetup: &testsetup
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - .citools/wait-for ${HOSTNAME} 7878
    - .citools/wait-for ${HOSTNAME} 8989

before_script:
  - git submodule update --init -- .citools
  - npm install

test:
  <<: *testsetup
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - .citools/wait-for ${HOSTNAME} 7878
    - .citools/wait-for ${HOSTNAME} 8989
    - npm test
  except:
    - develop
    - master

prerelease:
  <<: *testsetup
  stage: prerelease
  only:
    - develop
  script:
    - npm run build
    - .citools/lerna-publish prerelease

release:
  <<: *testsetup
  stage: release
  only:
    - master
  script:
    - npm run build
    - .citools/lerna-publish release
