image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - ./scripts/setup-ssh
  - npm install

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - ./scripts/wait-for ${HOSTNAME} 7878
    - ./scripts/wait-for ${HOSTNAME} 8989
    - ./test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - ./build
    - ./scripts/publish-staged

publish:
  stage: publish
  only:
    - tags
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - ./build
    - ./scripts/publish
