image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - ./wait-for ${HOSTNAME} 7878
    - ./wait-for ${HOSTNAME} 8989
    - ./test

publish:
  stage: publish
  only:
    - master
    - develop
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - ./publish
