image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install
  - ./node_modules/.bin/git-ssh-key setup
  - ssh-keyscan git.nativecode.net >> ~/.ssh/known_hosts

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - ./scripts/wait-for ${HOSTNAME} 7878
    - ./scripts/wait-for ${HOSTNAME} 8989
    - ./test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - ./scripts/setup-git
    - ./build
    - ./lerna version -c --yes --preid next -m 'bump'
    - ./lerna publish -c --yes --dist-tag next -m 'publish'

publish:
  stage: publish
  only:
    - master
  script:
    - ./scripts/setup-git
    - ./build
    - ./lerna version -c --yes -m 'bump'
    - ./lerna publish -c --yes -m 'publish'
