image: node:latest

stages:
- test
- publish

cache:
  paths:
  - node_modules

services:
- docker.io/nativecode/test-radarr:latest
- docker.io/nativecode/test-sonarr:latest

before_script:
- npm install

test:
  stage: test
  script:
  - cat /etc/hosts
  - ./wait-for nativecode-test-radarr 7878
  - ./wait-for nativecode-test-sonarr 8989
  - ./test

publish:
  stage: publish
  script:
  - ./build
  - ./publish
