image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RUNNER_IPADDRESS=$(getent hosts $HOSTNAME | awk '{ print $1 }')
    - export RADARR_ENDPOINT="http://${RUNNER_IPADDRESS}:7878/api"
    - export SONARR_ENDPOINT="http://${RUNNER_IPADDRESS}:8989/api"
    - ./wait-for ${RUNNER_IPADDRESS} 7878
    - ./wait-for ${RUNNER_IPADDRESS} 8989
    - ./test

publish:
  stage: publish
  script:
    - ./build
    - ./publish
