image: node:latest

stages:
- build
- test
- publish

cache:
  paths:
  - node_modules

before_script:
- npm install

build:
  stage: build
  script:
  - ./build

test:
  stage: test
  services:
  - name: nativecode/test-radarr:latest
    alias: test-radarr
  - name: nativecode/test-sonarr:latest
    alias: test-sonarr
  script:
  - ./wait-for test-radarr 7878
  - ./wait-for test-sonarr 8989
  - ./test

publish:
  stage: publish
  script:
  - ./publish
