image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - git submodule update --init -- .citools
  - npm install

test:
  stage: test
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - export RADARR_ENDPOINT="http://${HOSTNAME}:7878/api"
    - export SONARR_ENDPOINT="http://${HOSTNAME}:8989/api"
    - ./.citools/wait-for ${HOSTNAME} 7878
    - ./.citools/wait-for ${HOSTNAME} 8989
    - npm test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - npm test
    - ./.citools/lernapublish prerelease

publish:
  stage: publish
  only:
    - master
  script:
    - npm test
    - ./.citools/lernapublish release
