image: node:latest

stages:
  - test
  - prerelease
  - release

cache:
  paths:
    - node_modules

.testsetup: &testsetup
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - .citools/wait-for ${HOSTNAME} 7878
    - .citools/wait-for ${HOSTNAME} 8989
  variables:
    RADARR_ENDPOINT: "http://${HOSTNAME}:7878/api"
    SONARR_ENDPOINT: "http://${HOSTNAME}:8989/api"

before_script:
  - git submodule update --init -- .citools
  - npm install
  - source .ci-env

test:
  <<: *testsetup
  stage: test
  script:
    - npm test
  except:
    - develop
    - master

prerelease:
  <<: *testsetup
  stage: prerelease
  only:
    - develop
  script:
    - npm test
    - npm run pre-release

release:
  <<: *testsetup
  stage: release
  only:
    - master
  script:
    - npm test
    - npm run release
