image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install

test:
  stage: test
  services:
    - name: nativecode/test-radarr:latest
      alias: test-radarr
    - name: nativecode/test-sonarr:latest
      alias: test-sonarr
  script:
    - cat /etc/hosts
    - export RUNNER_IPADDRESS=$(getent hosts $HOSTNAME | awk '{ print $1 }')
    - ./wait-for ${RUNNER_IPADDRESS} 7878
    - ./wait-for ${RUNNER_IPADDRESS} 8989
    - ./test

publish:
  stage: publish
  script:
    - ./build
    - ./publish
