image: node:latest

cache:
  paths:
  - node_modules

before_script:
- npm install

test:
  services:
  - name: nativecode/test-radarr:latest
    alias: test-radarr
  - name: nativecode/test-sonarr:latest
    alias: test-sonarr
  script:
  - ./test
